version: '3.8'

networks:
  geolocate-network:
    driver: bridge

services:
  db-location:
    image: mongo:latest
    container_name: db-location
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: notset
      MONOG_INITDB_DATABASE: geolocate
    ports:
      - 27017:27017
    networks:
      - geolocate-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: db-location
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin # db-location root user
      ME_CONFIG_MONGODB_AUTH_PASSWORD: notset
      ME_CONFIG_BASICAUTH_USERNAME: admin # mongo-express web login
      ME_CONFIG_BASICAUTH_PASSWORD: notset
    ports:
      - 8081:8081
    networks:
      - geolocate-network
    depends_on:
      - db-location

  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    ports:
      - 8082:8080
    volumes:
      - ./src/test/resources/wiremock:/home/wiremock
    networks:
      - geolocate-network